#!/bin/bash

container_ip=$(docker inspect \
  -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' \
  app-data-monitoring-op-public-consumer-1)


curl -X POST $container_ip/initial-sync-jobs
echo ""



