(in-package :mu-cl-resources)

;; todo: move to external
(define-resource board-position-code ()
  :class (s-prefix "ext:BestuursfunctieCode")
  :properties `((:label :string ,(s-prefix "skos:prefLabel"))
                (:scope-note :string ,(s-prefix "skos:scopeNote")))
  :resource-base (s-url "http://data.vlaanderen.be/id/concept/BestuursfunctieCode/")
  :features '(include-uri)
  :on-path "board-position-codes")

;; (define-resource mandatary (agents-in-position)
(define-resource mandatary ()
  :class (s-prefix "mandaat:Mandataris")
  :properties `(
    ;; Indicates the location of the mandatary in the formally determined order of mandataries within the governing body in which the mandatary is located.
    (:ranking :string ,(s-prefix "mandaat:rangorde"))
    (:start-date :datetime ,(s-prefix "mandaat:start"))
    (:end-date :datetime ,(s-prefix "mandaat:einde"))) 
  ;; The theme or policy domain assigned to a mandatary.
  :has-many `((policy-domain :via ,(s-prefix "mandaat:beleidsdomein")
                             :as "policy-domain"))
  :has-one `((mandate :via ,(s-prefix "org:holds")
                      :as "holds")
              (membership :via ,(s-prefix "org:hasMembership")
                            :as "has-membership")
              (person :via ,(s-prefix "mandaat:isBestuurlijkeAliasVan")
                       :as "alias")
              (mandatary-status-code :via ,(s-prefix "mandaat:status")
                                     :as "status"))
  :resource-base (s-url "http://data.lblod.info/id/mandatarissen/")
  :features '(include-uri)
  :on-path "mandataries")

(define-resource mandatary-status-code ()
  :class (s-prefix "ext:MandatarisStatusCode")
  :properties `((:label :string ,(s-prefix "skos:prefLabel"))
                (:scope-note :string ,(s-prefix "skos:scopeNote")))
  :resource-base (s-url "http://data.vlaanderen.be/id/concept/MandatarisStatusCode/")
  :features '(include-uri)
  :on-path "mandatary-status-codes")

(define-resource mandate ()
  :class (s-prefix "mandaat:Mandaat")
  :has-one `((board-position-code :via ,(s-prefix "org:role")
                                  :as "role-board"))
  :has-many `((mandatary :via ,(s-prefix "org:holds")
                         :inverse t
                         :as "held-by")) 
  :resource-base (s-url "http://data.lblod.info/id/mandaten/")
  :features '(include-uri)
  :on-path "mandates")

(define-resource mandatary-status-code ()
  :class (s-prefix "ext:MandatarisStatusCode")
  :properties `((:label :string ,(s-prefix "skos:prefLabel"))
                (:scope-note :string ,(s-prefix "skos:scopeNote")))
  :resource-base (s-url "http://data.vlaanderen.be/id/concept/MandatarisStatusCode/")
  :features '(include-uri)
  :on-path "mandatary-status-codes")

(define-resource membership ()
  :class (s-prefix "org:Membership")
  :has-one `((parliamentary-group :via ,(s-prefix "org:organisation")
                      :as "inner-group")
             (mandatary :via ,(s-prefix "org:hasMembership")
                         :inverse t
                         :as "has-membership"))
  :resource-base (s-url "http://data.lblod.info/id/lidmaatschappen/")
  :features '(include-uri)
  :on-path "memberships")

(define-resource parliamentary-group ()
  :class (s-prefix "mandaat:Fractie")
  :properties `((:name :string ,(s-prefix "regorg:legalName"))) 
  :has-many `((governing-body :via ,(s-prefix "org:memberOf")
                              :as "member-of"))
  :has-one `((administrative-unit :via ,(s-prefix "org:linkedTo")
                              :as "linked-to"))
  :resource-base (s-url "http://data.lblod.info/id/fracties/")
  :features '(include-uri)
  :on-path "parliamentary-groups")

(define-resource person ()
  :class (s-prefix "person:Person")
  :properties `((:family-name :string ,(s-prefix "foaf:familyName"))
                (:first-name-used :string ,(s-prefix "persoon:gebruikteVoornaam")))
  :has-many `((mandatary :via ,(s-prefix "mandaat:isBestuurlijkeAliasVan")
                          :inverse t
                          :as "is-appointed-as")
              ;; (kandidatenlijst :via ,(s-prefix "mandaat:heeftKandidaat")
              ;;                  :inverse t
              ;;                  :as "is-kandidaat-voor")
              ;; (verkiezingsresultaat :via ,(s-prefix "mandaat:isResultaatVan")
              ;;           :inverse t
              ;;           :as "verkiezingsresultaten"))
  ;; :has-one `((geboorte :via ,(s-prefix "persoon:heeftGeboorte")
  ;;                      :as "geboorte")
  ;;            (identificator :via ,(s-prefix "adms:identifier")
  ;;                           :as "identificator")
  ;;            (geslacht-code :via ,(s-prefix "persoon:geslacht")
  ;;                           :as "geslacht")
  )
  :resource-base (s-url "http://data.lblod.info/id/personen/")
  :features '(include-uri)
  :on-path "people")

(define-resource policy-domain ()
  :class (s-prefix "ext:BeleidsdomeinCode")
  :properties `((:label :string ,(s-prefix "skos:prefLabel"))
                (:scope-note :string ,(s-prefix "skos:scopeNote")))
  :has-many `((mandatary :via ,(s-prefix "mandaat:beleidsdomein")
                          :inverse t
                          :as "mandataries"))
  :resource-base (s-url "http://data.vlaanderen.be/id/concept/BeleidsdomeinCode/")
  :features '(include-uri)
  :on-path "policy-domains")
